#!/usr/bin/env bash
# Configure nginx to trust Cloudflare proxy IPs and use CF-Connecting-IP.
# Run on EC2 as root after DNS is proxied (orange cloud).
set -euo pipefail

CF_CONF="/etc/nginx/conf.d/cloudflare-realip.conf"
TMP="$(mktemp)"

cat >"$TMP" <<'HDR'
# Cloudflare real IP — generated by scripts/nginx-cloudflare-realip.sh
real_ip_header CF-Connecting-IP;
real_ip_recursive on;
HDR

for url in \
  "https://www.cloudflare.com/ips-v4" \
  "https://www.cloudflare.com/ips-v6"; do
  curl -fsSL "$url" | while read -r cidr; do
    [[ -n "$cidr" ]] && echo "set_real_ip_from $cidr;"
  done >>"$TMP"
done

install -m 644 "$TMP" "$CF_CONF"
rm -f "$TMP"

nginx -t
systemctl reload nginx
echo "OK — $CF_CONF installed and nginx reloaded"
